- src/AlbyResponseError.test.ts
- src/AlbyResponseError.ts
- src/request.ts
- src/types.ts
fixes https://github.com/getAlby/alby-js-sdk/issues/25
> fix: set message on alby response error and export it

- src/OAuth2User.ts
Fixes https://github.com/getAlby/alby-js-sdk/issues/22
View no-whitespace diff: https://github.com/getAlby/alby-js-sdk/pull/23/files?diff=unified&w=1
> fix: refresh access token race condition

- package.json
- src/window.js
- yarn.lock
Fixes https://github.com/getAlby/alby-js-sdk/issues/27
> browserify

- .github/workflows/npm-publish.yml
- package.json
Adds publish workflow for automated package release on release tag.
> feat: add publish

- src/client.ts
- src/request.ts
- src/types.ts
Adds methods to get swap info & create new swaps.
> feat: swaps

- examples/nwc/get-balance.js
- package.json
- src/webln/NostrWeblnProvider.ts
- yarn.lock
Should be merged as soon as new version of Alby NWC is deployed.
> feat: convert balance from msat

- README.md
- src/client.ts
- src/types.ts
add invoices method to fetch all the transactions
> feat: add invoices method

- package.json
- src/webln/NostrWeblnProvider.ts
- yarn.lock
Fixes https://github.com/getAlby/js-sdk/issues/56
> chore: update nostr tools

- examples/nwc/get-info.js
- src/webln/NostrWeblnProvider.ts
extracted changes from https://github.com/getAlby/js-sdk/pull/152 and made some improvements
> feat: add NWC getInfo method

- .vscode/settings.json
- examples/nwc/list-transactions.js
- examples/nwc/lookup-invoice.js
- examples/nwc/make-invoice.js
- prettierrc.json
- src/webln/NostrWeblnProvider.ts
Adds listTransactions method to NWC provider
Extracted from https://github.com/getAlby/js-sdk/pull/152
> feat: add NWC listTransactions method

- src/client.ts
- src/helpers.ts
Fixes #212 
customRecords --> custom_records
> feat: update keysend args

- README.md
- examples/crypto-polyfill.js
- examples/nwc/client/get-balance.js
- examples/nwc/client/get-info.js
- examples/nwc/client/get-wallet-service-info.js
- examples/nwc/client/get-wallet-service-supported-methods.js
- examples/nwc/client/list-transactions.js
- examples/nwc/client/lookup-invoice.js
- examples/nwc/client/make-invoice.js
- examples/nwc/client/multi-pay-invoice.js
- examples/nwc/client/multi-pay-keysend.js
- examples/nwc/client/pay-invoice.js
- examples/nwc/client/pay-keysend.js
- examples/nwc/client/sign-message.js
- examples/nwc/client/subscribe.js
- examples/nwc/get-balance.js
- examples/nwc/get-info.js
- examples/nwc/keysend.js
- examples/nwc/list-transactions.js
- examples/nwc/lookup-invoice.js
- examples/nwc/make-invoice.js
- examples/nwc/multi-keysend.js
- examples/nwc/send-multi-payment.js
- examples/nwc/send-payment.js
- examples/nwc/sign-message.js
In Node.JS 20+ crypto already exists, and it also does not allow to assign directly to the global object.
> Fix: examples for nodeJS 20+

- src/NWCClient.ts
See https://github.com/getAlby/hub/pull/357
> feat: add metadata field to make_invoice

- package.json
- tsconfig.json
- yarn.lock
> chore: bump version

- package.json
- src/NWCClient.ts
TODO: propose as a spec change
> feat: add state property to Nip47Transaction

- .husky/commit-msg
- .husky/pre-commit
- README.md
- examples/nwc/auth_manual.html
- examples/nwc/client/auth_manual.html
- package.json
- src/webln/NostrWeblnProvider.ts
Fixes https://github.com/getAlby/js-sdk/issues/324
> fix: nwc auth docs, husky commit

- README.md
- src/client.ts
- src/types.ts
changes ain't deployed yet on getalby.com
> feat: add sign message method

- src/NWCClient.ts
Minor code cleanup, renaming methods, + one fix for the legacy version code ("nip44" should be "nip44_v2")
> Chore: nwc encryption feedback

- examples/lnclient/pay_ln_address.js
- examples/lnclient/paywall.js
- examples/lnclient/splitter.js
I was testing the new class and made this new example
> Add another ln client example

- docs/nwc.md
- docs/oauth.md
From https://github.com/getAlby/js-sdk/pull/352
> docs: fix more typos

- rollup.config.js
> chore: change umd bundle filename

- examples/.gitignore
- examples/oauth/.env.example
- examples/oauth/README.md
- examples/oauth/helper.ts
- examples/oauth/invoices.ts
- examples/package.json
- examples/yarn.lock
- package.json
fixes #478
@rolznz
i created a helper function to handle the auth flow and tested it in `invoices.ts`.
if this approach looks good to you, i’ll go ahead and add the helper function to the rest of the oauth examples.
you can follow the readme to test it out.
> feat(oauth): introduce helper for auth flow + test in invoices.ts
