getAlby/js-sdk

- README.md
The documentation omits that the `sendPayment` method returns a promise, and there is even an error in the example (missing an `await`)
> Fixes in doumentation for the client.sendPayment

- README.md
- package.json
- src/request.ts
- yarn.lock
Fixes https://github.com/getAlby/alby-js-sdk/issues/13
I didn't add a check for whether globalThis.fetch exists or not. It is not even guaranteed that globalThis will exist in old browsers and node versions.
> fix: remove cross-fetch

- src/OAuth2User.ts
- src/client.ts
- src/request.ts
Fixes #16 
Changes the rest function to have user-agent as param, also supports passing user_agent header as usual
(If both are passed, the one passed as the header will be considered)
> feat: add user_agent to options

- README.md
- package.json
> chore: rename alby js sdk package

- examples/nostr-wallet-connect.js
- src/webln/NostrWeblnProvider.ts
Adds get_balance method in nwc provider
See https://github.com/getAlby/nostr-wallet-connect/issues/113
> feat: add getbalance to nwc provider

- README.md
- package.json
- src/OAuth2User.ts
- yarn.lock
> token changed callback

- examples/nwc/lookup-invoice.js
- examples/nwc/make-invoice.js
- package.json
- src/webln/NostrWeblnProvider.ts
- yarn.lock
this is not actually a webln method. Not sure what to do here.
> feat: add lookup invoice to nwc webln provider

- README.md
- src/client.ts
- src/types.ts
**BREAKING CHANGE**
This is a keysend request so I think this naming makes more sense
> chore: rename sendToAlbyAccount to sendBoostagramToAlbyAccount

- README.md
- examples/decode-invoice.js
- src/client.ts
- src/types.ts
> feat: decode invoice

- src/types.ts
it will not exist for unsettled payments (currently not returned from the API)
> fix: make preimage optional

- src/webln/NostrWeblnProvider.ts
executeNip47Request was not awaited so the try/catch was ignored
> fix: get info fallback

- package.json
- src/types.ts
- src/webln/NostrWeblnProvider.test.ts
- src/webln/NostrWeblnProvider.ts
also rename c to name (already supported by nwc)
> fix: allow choosing request methods in authorization url

- examples/nwc/send-multi-payment.js
- package.json
- src/webln/NostrWeblnProvider.ts
- yarn.lock
~~This adds a dependency on lightning-tools to decode invoices, since the current spec returns payment hashes by default.
Or we could remove the dependency and generate ids and pass them to do the mapping, maybe that's better.~~ UPDATE: using `id` field of nwc to map instead of payment hash
The idea is that you can pay multiple invoices in a single request, but you need to know which ones succeeded and which ones failed. I was thinking an object like:
```
{
payments: [
{
paymentRequest: 'lnbc...',
preimage: '7c2c....'
},
...,
],
errors: [{
paymentRequest: 'lnbc...',
message: "Insufficient balance".
code: 1234
}]
}
```
Note: the error handling isn't done yet
> feat: add sendMultiPayment function and example

- examples/nwc/client/get-balance.js
- examples/nwc/client/get-info.js
- examples/nwc/client/list-transactions.js
- examples/nwc/client/lookup-invoice.js
- examples/nwc/client/make-invoice.js
- examples/nwc/client/multi-pay-invoice.js
- examples/nwc/client/multi-pay-keysend.js
- examples/nwc/client/pay-invoice.js
- examples/nwc/client/pay-keysend.js
- examples/nwc/keysend.js
- examples/nwc/multi-keysend.js
- package.json
- src/NWCClient.ts
- src/client.ts
- src/index.ts
- src/types.ts
- src/webln/NostrWeblnProvider.ts
Fixes https://github.com/getAlby/js-sdk/issues/182
WebLN and NWC are not 100% compatible. This PR splits the two so that the WebLN provider uses a NWC Client (which can also be used on its own as it has more detailed responses and is less restricted than WebLN).
The WebLN provider should be unchanged.
This PR also adds multi_pay_keysend.
TODOs:
> feat: Split NWC client from NostrWeblnProvider

- src/NWCClient.ts
This should make it more compatible and aligned with the spec
> Send empty params for `get_info` and `get_balance`

- examples/nwc/client/get-wallet-service-supported-methods.js
- src/NWCClient.ts
As per https://github.com/nostr-protocol/nips/blob/master/47.md#theory-of-operation to get "info" (actually just supported methods) from the relay
> feat: add NWC client method to get wallet service supported methods

- package.json
- src/NWCClient.ts
> fix: use actual error objects in NWC Client

- package.json
- src/OAuth2User.ts
- yarn.lock
as the events package does not play nicely in a module import setup this is an alternative. 
https://www.npmjs.com/package/eventemitter3
> chore: try eventemitter3

- examples/nwc/client/subscribe.js
- src/NWCClient.ts
For https://github.com/getAlby/nostr-wallet-connect-next/pull/183
Also removes some unnecessary kind checks in other methods since they already use a filter which specifies the kind
Example output:
```
$ node examples/nwc/client/subscribe.js 
Waiting for notifications...
Got notification {
result: {
type: 'incoming',
invoice: 'lnbc10n1pnqn99ydqafet5xgzrd35k2mn5ypjhsctdwpkx2np4qtuqfrmmrt9nf5fg4ahkraszktyl98u4zj54mp427kcztlyjdyts7pp5gkhls9e6aj8yjcjvsdylp03kl0g6rlewxyk2yv3gl6ktk9uhascssp5ndqrw7spngrgg5fnf4dud639ez5lkhxyuepzk6e5m2f4879jeexs9qyysgqcqpcxqyz5vqrzjq2w2zkkjagc80a0s2fxyex7zv6z5c99eljqmnnpaddywy3s27ylk2zkga9t8zhj93uqqqqlgqqqqqzsqygrzjqwh05slmksqfkgdyz2wst9fewjmah2amldg3jg2pqzqgvr723mslp4pgjtsk665zd5qqqqlgqqqqqzsqygrzjqvdnqyc82a9maxu6c7mee0shqr33u4z9z04wpdwhf96gxzpln8jcrapyqqqqqqqesuq …
```
> feat: subscribe to NIP-47 notifications

- examples/nwc/client/sign-message.js
- examples/nwc/sign-message.js
- src/NWCClient.ts
- src/webln/NostrWeblnProvider.ts
Related to https://github.com/getAlby/nostr-wallet-connect-next/issues/108
Example output:
```
node examples/nwc/sign-message.js 
{
message: 'Hello, world!',
signature: 'd9s5fyzwmjpyxej81kaz1iqqhn356epba4eokducjwc3n517dbg1sopi9hqkjunhpx5af4hxo9xrzx3y95x4ra73fko1qpffuajio1au'
}
```
> feat: add NWC sign message method

- examples/nwc/client/get-wallet-service-info.js
- src/NWCClient.ts
Update to use `notifications` capability and read notification types from notification tag 
https://github.com/nostr-protocol/nips/pull/1164
> feat: read supported notification types from wallet service info notifications tag

- src/NWCClient.ts
Adds `payment_sent` support in NIP47 Notifications
> feat: add payment_sent notification

- examples/nwc/client/multi-pay-keysend.js
- examples/nwc/client/pay-keysend.js
- package.json
- src/webln/NostrWeblnProvider.ts
With WebLN keysend TLVs, the value is passed as plaintext:
https://www.webln.guide/building-lightning-apps/webln-reference/webln.keysend
In NIP-47 spec the value should be hex encoded:
https://github.com/nostr-protocol/nips/blob/master/47.md#pay_keysend
This PR fixes the NostrWeblnProvider to pass the TLV values hex-encoded instead of plaintext.
> fix: pass TLV value as hex from nwc webln provider to nwc client keysend

- README.md
This does not add all the documentation as in https://github.com/getAlby/js-sdk/pull/230 but it aims to give enough info for the developer make an informed choice on what protocol / library to use and quickly get started.
I think we should then later split the documentation of the three different ways to use the JS SDK (NWC, WebLN, Alby API) into separate md files to avoid the README getting too long
> docs: add NWCClient to README

- src/NWCClient.ts
Not all NWC wallet services support notifications - this should be optional.
> fix: make notifications optional in info response

- examples/nwc/client/get-budget.js
- src/NWCClient.ts
- src/webln/NostrWeblnProvider.ts
Fixes https://github.com/getAlby/js-sdk/issues/261
> feat: add get_budget to NWCClient

- src/NWCClient.ts
Alby Hub can store this data, enabling interesting applications to be developed, and finally enable a nice way to store payment metadata.
> feat: allow passing metadata in nwc pay_invoice and multi_pay_invoice

- examples/crypto-polyfill.js
- examples/nwc/client/get-balance.js
- examples/nwc/client/get-budget.js
- examples/nwc/client/get-info.js
- examples/nwc/client/get-wallet-service-info.js
- examples/nwc/client/get-wallet-service-supported-methods.js
- examples/nwc/client/list-transactions.js
- examples/nwc/client/lookup-invoice.js
- examples/nwc/client/make-invoice.js
- examples/nwc/client/multi-pay-invoice.js
- examples/nwc/client/multi-pay-keysend.js
- examples/nwc/client/pay-invoice.js
- examples/nwc/client/pay-keysend.js
- examples/nwc/client/sign-message.js
- examples/nwc/client/subscribe.js
- examples/nwc/get-balance.js
- examples/nwc/get-info.js
- examples/nwc/keysend.js
- examples/nwc/list-transactions.js
- examples/nwc/lookup-invoice.js
- examples/nwc/make-invoice.js
- examples/nwc/multi-keysend.js
- examples/nwc/send-multi-payment.js
- examples/nwc/send-payment.js
- examples/nwc/sign-message.js
- package.json
- src/NWCClient.ts
- src/webln/NostrWeblnProvider.ts
- yarn.lock
This updates the nostr-tools package to 2.9.4 (the latest is 2.10.4 but it has a timeout leak, opened a [PR](https://github.com/nbd-wtf/nostr-tools/pull/461) to fix it there)
> chore(deps): update nostr-tools package

- src/NWCClient.ts
Example response:
```
{
alias: 'NWC',
color: '#897FFF',
pubkey: '03a078ec02e002be52c961b3fcc3c0d92f096b8a86844e256ad6f03aadbbc703ce',
network: 'signet',
block_height: 1766902,
block_hash: '000000e5c972792fafc5ac45ffe216a2d44340f7de813267149302e4e4a60573',
methods: [
'pay_invoice',
'pay_keysend',
'multi_pay_invoice',
'multi_pay_keysend',
'get_info',
'get_balance',
'make_invoice',
'lookup_invoice',
'list_transactions',
'sign_message',
'get_budget'
],
notifications: [ 'payment_received', 'payment_sent' ],
metadata: { app_store_app_id: 'habla-news', id: 57, name: 'Habla News' }
}
```
> chore: add optional metadata field to get_info response

- package.json
- yarn.lock
Reverts getAlby/js-sdk#289
Since the version 2.10.4 has a timeout leak which will be fixed in the next release.
> Revert "chore(deps): bump nostr-tools from 2.9.4 to 2.10.4"

- package.json
- src/OAuth2User.ts
- src/eventEmitter/EventEmitter.ts
- src/types.ts
- yarn.lock
remove emittery package causing build issues
> feat: custom EventEmitter classes

- package.json
- src/NWAClient.ts
- src/NWCClient.ts
Code is copied from NWCClient `subscribeNotifications` (which seems to be working well there). In this case I think it's more complicated to try extracting the duplicated code, maybe we can revisit this if we have a third case where we subscribe like this.
Tested with Zappy Bird on iOS, plus locally with shutting down and restarting local relay
> fix: re-subscribe after relay disconnections in NWAClient

- docs/lnclient.md
- examples/lnclient/paywall.js
- examples/lnclient/splitter.js
- src/lnclient/ReceiveInvoice.ts
Based on the updated comments, some things can be simplified/improved with the `onTimeout` method.
`ReceiveInvoice` has changed so it does not have async methods, so that they can be chained, and also the `async onPaid` function was a bit strange because all it returned was a ~~timeout~~ unsubscribe method (not once the invoice was paid).
> feat: add lnclient receive timeout for ReceiveInvoice class

- docs/lnclient.md
- examples/lnclient/pay_ln_address.js
- examples/lnclient/paywall.js
- examples/lnclient/splitter.js
- src/lnclient/ReceiveInvoice.ts
@rolznz how about we just add comment on the `client.close()` ?
> docs: add some comments to the examples

- src/nwc/types.ts
Only adds identifier as description is not widely used and is usually the same message everytime (ex: "Sats for Adithya Vardhan")
> chore: add recipient_data to tx metadata

- examples/nwc/keysend.ts
updated node id to `02947ea84b359c2e902c10e173aa209a36c2f92a6143c73170eb72b2077c592187`
fixes #441
> fix: update node id for keysend examaple

- docs/nwc-wallet-service.md
- docs/nwc.md
- examples/lnclient/pay_ln_address.ts
- examples/lnclient/paywall.ts
- examples/lnclient/splitter.ts
- examples/nwc/get-balance.ts
- examples/nwc/get-info.ts
- examples/nwc/keysend.ts
- examples/nwc/list-transactions.ts
- examples/nwc/lookup-invoice.ts
- examples/nwc/make-invoice.ts
- examples/nwc/multi-keysend.ts
- package.json
- rollup.config.js
- src/index.ts
- src/oauth/index.ts
- tsconfig.json
- yarn.lock
This fixes the long pending bundling issues using rollup.
We now export both esm and cjs files, and also types in such a way that devs can do either:
```js
import { CreateSwapResponse } from "@getalby/sdk";
// or
import { CreateSwapResponse } from "@getalby/sdk/oauth";
// actually it's best to do it like this so compiler understands that we only need the typing
import type { CreateSwapResponse } from "@getalby/sdk/oauth";
```
And this removes export as nwc, oauth etc. So now:
```js
import { nwc } from "@getalby/sdk";
const nwcClient = new nwc.NWCClient({
nostrWalletConnectUrl: loadNWCUrl(),
});
```
will not work, we should instead do:
```js
import { NWCClient } from "@getalby/sdk/nwc";
// or
import { NWCClient } from "@getalby/sdk";
const nwcClient = new NWCClient({
nostrWalletConnectUrl: …
```
> feat: add subpath imports and fix bundling issues

- src/nwc/NWCClient.ts
I noticed one of my apps was never able to reconnect even though the relay was working fine. It kept logging `failed to connect to relay wss://relay.getalby.com/v1`. Still needs to be debugged what went wrong.
> chore: log connection error when failing to reconnect to relay

- src/oauth/types.ts
- src/oauth/utils.ts
This PR fixes issue #474 with query parameter handling in invoice requests: 
* **Updated `buildQueryString`**
* Added support for nested objects (e.g. `q[created_at_gt]`) so they no longer serialize as `[object Object]`.
* Dropped empty/null/undefined entries to prevent stray `&&` in query strings.
* **Updated `GetInvoicesRequestParams` type**
* Added support for `q.before` (invoice ID pagination).
* Changed `created_at_lt` / `created_at_gt` from `string` to `number` to correctly match the type expected in the docs.
> fix(query): improve buildQueryString for nested params and update GetInvoicesRequestParams
